name: Build Vue
on: [push]
jobs:
  build_vue:
    runs-on: ubuntu-latest
    name: Build Vue
    steps:
    - uses: actions/checkout@v2
    - name: Setup Node
      uses: actions/setup-node@v2
      with:
        node-version: '18'
    - name: Install dependencies
      run: npm ci
    - name: Build
      run: npm run build
      env:
        VUE_APP_KEY: ${{ secrets.VUE_APP_KEY }}
        VUE_APP_URL: ${{ secrets.VUE_APP_URL }}
    - name: Deploy
      run: |
        cd dist
        ln -s index.html 404.html
        git config --global user.email "matthewpchoy@gmail.com"
        git config --global user.name "Matt.Choy"
        git init
        git add -A
        git commit -m 'deploy'
        git push -f https://MattPChoy:${{ secrets.GITHUB_TOKEN }}@github.com/MattPChoy/CustomComponents.git main:gh-pages
